name: maven compile test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: replace platform
      run: sed -i "s/SONIC_PLATFORM/linux-x86_64/g" pom.xml
    - name: Validate and Compile with Maven
      run: mvn validate compile
